# =========================================================
# GitHub Actions: Build and deploy Python app to Azure Web App
# Target: /backend folder
# =========================================================
name: Build and deploy Python app to Azure Web App - Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive backend app
        run: |
          cd backend
          zip -r ../backend.zip .
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # Required for requesting the JWT
      contents: read    # Required for checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-backend
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8B6C70A182F9481DA9DD95916875D8D2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BF8DC31FED7A45A99BDFC502A31FE65F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B90AFC8C34424235B39B2D9056CDE4B0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Backend'
          slot-name: 'Production'
          package: backend.zip
